title: TLYNT
description: Release Notes
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
show_downloads: false
logo: /assets/img/logo.png
logo_app: /assets/img/logo-app.png
logo_portal: /assets/img/logo-portal.png
public_website: https://jointTLYNT.com
